// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdascLGtUx2wjcHNlSr6BvAlLdiCDXk-k',
    appId: '1:879720432733:web:74e3f2e427a421e5d9f9b4',
    messagingSenderId: '879720432733',
    projectId: 'pro-bouncer',
    authDomain: 'pro-bouncer.firebaseapp.com',
    storageBucket: 'pro-bouncer.appspot.com',
    measurementId: 'G-FY9LY6LKRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv56I4Az4GuTw9RbO3E6J89WOTC1zHV7s',
    appId: '1:879720432733:android:c1c4949043dc0735d9f9b4',
    messagingSenderId: '879720432733',
    projectId: 'pro-bouncer',
    storageBucket: 'pro-bouncer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoTGLxIfdfe57HejILrDDXo-8UVq9ckjM',
    appId: '1:879720432733:ios:e0987fd6ea3d01dcd9f9b4',
    messagingSenderId: '879720432733',
    projectId: 'pro-bouncer',
    storageBucket: 'pro-bouncer.appspot.com',
    iosBundleId: 'com.example.feb24ProVisitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoTGLxIfdfe57HejILrDDXo-8UVq9ckjM',
    appId: '1:879720432733:ios:f94e6f3b6c325134d9f9b4',
    messagingSenderId: '879720432733',
    projectId: 'pro-bouncer',
    storageBucket: 'pro-bouncer.appspot.com',
    iosBundleId: 'com.example.feb24ProVisitor.RunnerTests',
  );
}
